name: example
description: A new Flutter project.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  copy_with:
    path: ../copy_with


dev_dependencies:
  build_runner: ^2.4.15
  copy_with_gen:
    path: ../copy_with_gen

