builders:
  copy_with_gen:
    target: ":copy_with_gen"
    import: "package:copy_with_gen/builder.dart"
    builder_factories: [ "copyWith"]
    build_extensions: { ".dart": [ ".g.part" ] }
    auto_apply: dependents
    build_to: cache
    applies_builders: [ "source_gen|combining_builder" ]
