name: copy_with_gen
description: generates a copyWith method for classes marked with @copyWith annotation
  (generator)
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  analyzer: ^7.3.0
  build: ^2.4.2
  copy_with:
    path: ../copy_with
  jinja: ^0.6.2
  source_gen: 2.0.0
  package_config: ^2.2.0


